### ISSUE TITLE
Matlab Crash when running demo.m

### ISSUE THREAD

**Issue by weiweikong** [chrischoy/enriching_object_detection#1]
- Ubuntu 14.04
- Matlab 2015b
- OSG installed at `/usr/local` with version `libosg.so.146`

When run `demo.m` got

```
Error reading file Carpet.jpg: file not found
Warning: Cannot create texture Carpet.jpg
Error reading file Wood_Tri.jpg: file not found
Warning: Cannot create texture Wood_Tri.jpg
ViewerBase::configureAffinity() numProcessors=24
  databasePagers = 1
ViewerBase::configureAffinity() numProcessors=24
  databasePagers = 1
_forceVertexArrayObject = 0
_forceVertexBufferObject = 0
ObjectWrapperManager::addCompressor(): 'null' already exists.
ObjectWrapperManager::addCompressor(): 'zlib' already exists.
```

then Matlab carshed.

**Comment by purirohan** [comment]
@weiweikong were you able to resolve this issue? I'm encountering the same problem.

**Comment by weiweikong** [comment]
@purirohan No. I tried several ways, but still failed. Also, there is no reply from the author. Any idea?

**Comment by chrischoy** [comment]
This seems to be the OSGRenderer-matlab interoperability problem. I'll look into this in the OSGRenderer repo.

**Comment by chrischoy** [comment]
Closing the thread for an issue in the dependency. Please refer to https://github.com/chrischoy/OSGRenderer/issues/9.

**Comment by weiweikong** [comment]
Thanks. @chrischoy
